### ISSUE TITLE
Default icon names

### ISSUE THREAD

**Issue by CVYY39** [jessesquires/iOS-icons-script#2]
The default icon names don't match the schema used for Apple's iconutil, even though they are very close. 

iconutil requires:

- `icon_16x16.png`
- `icon_16x16@2x.png`
- `icon_32x32.png`
- `icon_32x32@2x.png`
- `icon_128x128.png`
- `icon_128x128@2x.png`
- `icon_256x256.png`
- `icon_256x256@2x.png`
- `icon_512x512.png`
- `icon_512x512@2x.png`

This script produces:

- `Icon-16x16.png`
- `Icon-16x16@2x.png`
- `Icon-32x32.png`
- `Icon-32x32@2x.png`
- `Icon-128x128.png`
- `Icon-128x128@2x.png`
- `Icon-256x256.png`
- `Icon-256x256@2x.png`
- `Icon-512x512.png`
- `Icon-512x512@2x.png`

It seems like minor name tweaks would make iconutil work without requiring a separate rename. Any reason not to change?

**Comment by jessesquires** [comment]
I wasn't familiar with `iconutil`, but I found [this documentation](https://developer.apple.com/library/archive/documentation/GraphicsAnimation/Conceptual/HighResolutionOSX/Optimizing/Optimizing.html). (posting for posterity)

This sounds like a reasonable change to me! I would happily accept a PR for this @CVYY39 😄

**Comment by CVYY39** [comment]
Happy to! But it looks like you'd need to add me as a collaborator so I can do a branch/pull request.

**Comment by jessesquires** [comment]
You should be able to fork, then pull request 😄 Does that work?

**Comment by pkclsoft** [comment]
Sounds like a great enhancement.  I've scripts for other project that generate the asset catalog from the images which removes the manual step of moving everything in with drag and drop, but I haven't updated it to work with this yet.

**Comment by jessesquires** [comment]
@pkclsoft that also sounds like a great idea 💯

**Comment by pkclsoft** [comment]
The fun thing about using asset catalogs for the icons is that it doesn't really matter what we call each individual icon file, so long as it's put in the right place, and referenced from the JSON file properly.

**Comment by pkclsoft** [comment]
I've committed a small change to the iOS script, and added my bash script for generating the asset catalogs (ios and watch only).  It would be good to rewrite it in JS, but I don't have time right now to teach myself JS such that I'm confident about the result.  I've not created a pull-request for this because I'm not sure you want a bash script in the main repo.

**Comment by jessesquires** [comment]
hey @pkclsoft -- sorry just saw this! feel free to submit a PR 😄 

in 41fa261 i made the name change requested in the original comment for this issue.

> I've committed a small change to the iOS script

just updated this, so you'll want to rebase

>  I'm not sure you want a bash script in the main repo

that's fine with me!
