### ISSUE TITLE
Script does not maintain transparent layer in Photoshop 2020

### ISSUE THREAD

**Issue by bobbydank** [jessesquires/iOS-icons-script#6]
I create a png icon with a transparent layer. I run the script on it and all of the icons it creates are on a white layer.

**Comment by jessesquires** [comment]
Thanks @bobbydank !  Which icons were you creating? 

This was changed in #4. cc @pkclsoft 

---

iOS icons definitely shouldn't have transparency. However, now I'm realizing that iMessage stickers and macOS icons **should** allow this.

**Comment by bobbydank** [comment]
Sorry. I was using the iOS icons script.

**Comment by jessesquires** [comment]
Thanks for clarifying! 😄 

In that case, this is expected behavior. iOS icons should not have transparency. The system will apply the rounded corners.
